# Generated by Django 2.1.4 on 2018-12-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
