# Generated by Django 2.1.5 on 2019-02-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181214_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='downloads',
            field=models.IntegerField(default=1),
        ),
    ]
