# Generated by Django 2.1.7 on 2019-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190226_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='size',
            field=models.CharField(default=14, max_length=255),
            preserve_default=False,
        ),
    ]
