# Generated by Django 2.1.7 on 2019-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_books_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
