# Generated by Django 2.1.7 on 2019-03-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_books_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='size',
            field=models.FloatField(null=True),
        ),
    ]
