# Generated by Django 2.2.1 on 2019-05-16 13:17

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20190307_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='books',
            name='downloads',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pdf',
            field=models.FileField(upload_to=books.models.Books.path_and_rename),
        ),
        migrations.AlterField(
            model_name='books',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='typology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Type'),
        ),
    ]
