# Generated by Django 2.1.7 on 2019-03-15 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20190315_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='uploader',
            field=models.ForeignKey(on_delete=models.SET('Jonathan'), to=settings.AUTH_USER_MODEL),
        ),
    ]
