# Generated by Django 2.1.7 on 2019-03-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20190315_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='downloads',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
