# Generated by Django 2.1.7 on 2019-03-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20190316_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(default='slug-test'),
            preserve_default=False,
        ),
    ]
