# Generated by Django 2.1.7 on 2019-03-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20190316_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='categories',
            name='category',
            field=models.ManyToManyField(to='books.Books'),
        ),
    ]
