# Generated by Django 2.1.7 on 2019-03-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_auto_20190316_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category',
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(to='books.Categories'),
        ),
    ]
