# Generated by Django 2.1.7 on 2019-03-16 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20190316_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='typology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Type'),
        ),
    ]
