# Generated by Django 2.1.7 on 2019-03-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_auto_20190316_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('name',)},
        ),
    ]
