# Generated by Django 2.1.7 on 2019-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_auto_20190317_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
