# Generated by Django 2.1.7 on 2019-03-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_auto_20190317_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, default='/res/no-cover.jpg', upload_to='images/'),
        ),
    ]
