# Generated by Django 2.1.7 on 2019-05-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_auto_20190318_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='books',
            name='level',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
