# Generated by Django 2.2.1 on 2019-05-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_auto_20190502_1826'),
        ('books', '0034_auto_20190502_1836'),
    ]

    operations = [
    ]
