# Generated by Django 2.1.7 on 2019-03-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190316_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='go', upload_to='avatar/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=20),
        ),
    ]
