# Generated by Django 2.1.7 on 2019-03-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190316_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='accounts/templates/icon/icon.png', upload_to='avatar/'),
        ),
    ]
